### ISSUE TITLE
"your device isn't compatible with this version

### ISSUE THREAD

**Issue by rachelsdurden** [matejdro/WearMusicCenter#15]
This app was working on my device yesterday. I ran an update and I got the "your device is incompatible" error. Not a lot of further info.

Wearos 2.31 android security patch Feb 1 2021

Model is Fossil Julianna HR

**Comment by matejdro** [comment]
Yeah, I'm afraid app is currently unavailable because Google took it down. I've made an appeal and will hopefully get it reinstated asap.

Until then you can either wait or sideload the apk.

**Comment by rachelsdurden** [comment]
Interesting. Did they say why or was it just out of the blue?

**Comment by matejdro** [comment]
Their reason was only "App does not work"

**Comment by matejdro** [comment]
This should be resolved now
