### ISSUE TITLE
not support wear os china edition

### ISSUE THREAD

**Issue by fireinice** [matejdro/WearMusicCenter#17]
by android developer doc, it needs to add some deps in bundle

https://developer.android.com/training/wearables/creating-app-china?hl=en

**Comment by matejdro** [comment]
Hm, from what I see, all of these are already in. Does it just not work in china for you?

**Comment by fireinice** [comment]
by the doc, it should assign the version of the play service by 10.2.0

**Comment by fireinice** [comment]
by some reasons, the china edition use a different version "wearos by google" app from google play. I thought that's the point.

**Comment by matejdro** [comment]
It looks like chinese version only supports very old play services 10.2.0, which this app is not compatible with anymore.

If you want, you can get [https://github.com/matejdro/WearMusicCenter/tree/d0071bdd3d7e89cea4a4885b4b681558f0c7151e](this old revision) of the app, fork it and fix china support. I will not do so myself.

**Comment by fireinice** [comment]
I'll try, but I'm really greenhand for android developing. Any chance give me some clues how to build apk for wear part? I only could get apk in wear/release directory and it looks like the phone part by size. Thanks
