### ISSUE TITLE
Show watch battery percentage (Feature Request)

### ISSUE THREAD

**Issue by Zerubel** [matejdro/WearMusicCenter#19]
If possible, could the watch battery percentage be displayed in place of an icon, much like the current feature to show the time at the top? It'd be very helpful, esp as my watch (ticwatch E3) is an lcd screen so AOD tends to use up more battery. (I like AOD, even with that limitation, just a little reminder of when i should stop using the AOD is nice). Preferably it wouldn't replace the clock, but could be shown in addition to it - maybe on the bottom?

Thank you for this wonderful app!

**Comment by matejdro** [comment]
Sorry, I don't think I will be adding this myself (I think it is a bit out of scope for the app), but you are free to make a PR and will be added.
