### ISSUE TITLE
notification access crashes app on Android 13

### ISSUE THREAD

**Issue by howels** [matejdro/WearMusicCenter#21]
Using lineageOS 20 (android 13) with the app sideloaded on a pixel watch. The phone app crashes when going into the "open music centre automatically" setting 

I have enabled notification access for the app in Android permissions

**Comment by matejdro** [comment]
Can you give me the logcat output of the crash?

**Comment by howels** [comment]
> Can you give me the logcat output of the crash?

[logcat-musiccenter.txt](https://github.com/matejdro/WearMusicCenter/files/13476962/logcat-musiccenter.txt)

**Comment by matejdro** [comment]
Which version do you have? 1.9.2 fixed several crashes like this: https://github.com/matejdro/WearMusicCenter/releases/tag/1.9.2

**Comment by howels** [comment]
> Which version do you have? 1.9.2 fixed several crashes like this: https://github.com/matejdro/WearMusicCenter/releases/tag/1.9.2

ok, looks like that was released the day after I checked last. Updated and it is resolved - thanks for updating the code.
