### ISSUE TITLE
App does not function on Pixel Watch 3

### ISSUE THREAD

**Issue by pablomentabo** [matejdro/WearMusicCenter#24]
When you try to open it you are met with this message:

![screenshot-2024-09-11-16-57-05](https://github.com/user-attachments/assets/78965d30-ca4f-4d32-96e6-e1afa2885443)

When you click "Open Settings" you are met with this message: 

![screenshot-2024-09-11-16-57-24](https://github.com/user-attachments/assets/18b5c2ae-cd35-491e-a0f1-71ef6552e01f)

When you click OK you are taken to this screen

![screenshot-2024-09-11-16-57-45](https://github.com/user-attachments/assets/f4facb40-a480-4b73-b923-0e3c785e7616)

**Comment by matejdro** [comment]
You appear to have knstalled phone app on the watch. You need to install the 'wear.apk'

**Comment by pablomentabo** [comment]
Thanks, totally my fault then. That fixed it
